### ISSUE TITLE
Kanban issue for review

### ISSUE THREAD

**Issue by til2to** [til2to/javascript-capstone#21]
In this milestone, Kanban board was setup using a copy of microverse's template.

- [ ] https://github.com/til2to/javascript-capstone.
- [ ] https://github.com/til2to/javascript-capstone/projects?query=is%3Aopen
- [ ] We are a team of two: Supreeti and Dennis

**Comment by codecaiine** [comment]
Hi @til2to @supreeti , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights


## Required Changes ♻️
- [ ] I noticed that you forgot to assign some cards to team members. Please make sure all cards are assigned to team members 👍 
![asign](https://github.com/til2to/javascript-capstone/assets/6615394/58c01c5c-1bae-45b8-9c12-47022e5da2e5)

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by til2to** [comment]
I taught these once are group task so no need to assign. kindly check that

**Comment by til2to** [comment]
Ok. done now

**Comment by V-Blaze** [comment]
Hi @til2to  , 

# Approved 🟢 🟢 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![giphy](https://user-images.githubusercontent.com/107632780/229644741-7dea3027-bf3f-4416-855b-46095e3bf6d5.gif)

## Highlights

- Kanban board setup correctly💯
-  Tasks assigned to each student correctly👍🟢 👍

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
